**Assignment 7**

**Name : Ramakrishna Reddy Are**

**Roll No. : 197212**

**Section : BTech III year CSE-B**

**Date : 20-03-2022**



---


**1. Simple Neural Network Model Using Tensorflow**


---



In [ ]:
# importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from sklearn.model_selection import train_test_split  

***importing the dataset [insurance_data.csv](https://)***

In [ ]:
# loading the dataset
dataset = pd.read_csv('insurance_data.csv')
dataset.head()

age  Affordability  bought_insurance
0   22              1                 0
1   25              1                 0
2   47              0                 1
3   52              1                 0
4   46              1                 1

In [ ]:
# preparing the dataset in required format
# assigning values to independent and dependent variable
X = dataset.iloc[:,:-1]
Y = dataset.iloc[:,-1]
print(X)
print(Y)

    age  Affordability
0    22              1
1    25              1
2    47              0
3    52              1
4    46              1
5    56              0
6    55              1
7    60              1
8    62              1
9    61              1
10   18              0
11   28              1
12   27              0
13   29              0
14   49              1
15   55              1
16   25              0
17   58              0
18   19              1
19   18              1
20   21              1
21   26              0
22   40              1
23   45              0
24   50              1
25   54              1
26   23              1
0     0
1     0
2     1
3     0
4     1
5     1
6     0
7     1
8     1
9     1
10    0
11    0
12    0
13    0
14    1
15    1
16    1
17    1
18    0
19    0
20    0
21    0
22    1
23    1
24    1
25    1
26    0
Name: bought_insurance, dtype: int64


In [ ]:
# Splitting the X and Y Dataset into the Training set and Test set
# Splitting the dataset into 20% test data and 80% train data
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)  

In [ ]:
# Printing the splitted data
print("X Train\n",X_train)
print("Y Train\n",Y_train)
print("X test\n",X_test)
print("Y test\n",Y_test)

X Train
     age  Affordability
23   45              0
13   29              0
19   18              1
20   21              1
16   25              0
1    25              1
10   18              0
26   23              1
25   54              1
8    62              1
6    55              1
4    46              1
18   19              1
9    61              1
7    60              1
22   40              1
3    52              1
0    22              1
21   26              0
15   55              1
12   27              0
Y Train
 23    1
13    0
19    0
20    0
16    1
1     0
10    0
26    0
25    1
8     1
6     0
4     1
18    0
9     1
7     1
22    1
3     0
0     0
21    0
15    1
12    0
Name: bought_insurance, dtype: int64
X test
     age  Affordability
2    47              0
24   50              1
14   49              1
17   58              0
5    56              0
11   28              1
Y test
 2     1
24    1
14    1
17    1
5     1
11    0
Name: bought_insurance, dtype: int64


In [ ]:
# Perform Feature Scaling - Standardizing the dataset
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [ ]:
# printing values after feature scaling
print("X Train\n",X_train)
print("X Test\n",X_test)

X Train
 [[ 0.48375239 -1.58113883]
 [-0.5195859  -1.58113883]
 [-1.20938097  0.63245553]
 [-1.02125504  0.63245553]
 [-0.77042047 -1.58113883]
 [-0.77042047  0.63245553]
 [-1.20938097 -1.58113883]
 [-0.89583775  0.63245553]
 [ 1.04813017  0.63245553]
 [ 1.54979931  0.63245553]
 [ 1.11083881  0.63245553]
 [ 0.54646103  0.63245553]
 [-1.14667232  0.63245553]
 [ 1.48709067  0.63245553]
 [ 1.42438203  0.63245553]
 [ 0.17020917  0.63245553]
 [ 0.92271289  0.63245553]
 [-0.9585464   0.63245553]
 [-0.70771182 -1.58113883]
 [ 1.11083881  0.63245553]
 [-0.64500318 -1.58113883]]
X Test
 [[ 0.60916967 -1.58113883]
 [ 0.7972956   0.63245553]
 [ 0.73458696  0.63245553]
 [ 1.29896474 -1.58113883]
 [ 1.17354746 -1.58113883]
 [-0.58229454  0.63245553]]


***Building the Artificial Neural Network***

In [ ]:
# Importing keras
import keras
from keras.models import Sequential  
from keras.layers import Dense

***Initializing the Artificial Neural Network***

In [ ]:
ANN = Sequential()

***Adding the input and first hidden layer***
***
1.   input layer nodes : 2
2.   1st hidden layer nodes : 6
3.   Activation Function : Relu
***

In [ ]:
ANN.add(Dense(6,kernel_initializer='uniform',activation='relu',input_dim=2))

***Adding the second hidden layer***
***
1.   input layer nodes : 6 (output of 1st hidden layer)
2.   2nd hidden layer nodes : 6
3.   Activation Function : Relu
***


In [ ]:
ANN.add(Dense(6,kernel_initializer='uniform',activation='relu',input_dim=6))

***Adding the output layer***
***
*   Output layer nodes : 1
***

In [ ]:
ANN.add(Dense(1,kernel_initializer='uniform',activation='sigmoid'))

***Training the Artificial Neural Network***<br>
***compile :***
***
*   optimizer : "adam" performs gradient descent
*   cost function : binary_crossentropy

***

In [ ]:
ANN.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

***Fitting the ANN to Training Set***

In [ ]:
ANN.fit(X_train,Y_train,batch_size=5,epochs=200)

Epoch 1/200
5/5 [==============================] - 1s 3ms/step - loss: 0.6931 - accuracy: 0.5238
Epoch 2/200
5/5 [==============================] - 0s 2ms/step - loss: 0.6929 - accuracy: 0.5714
Epoch 3/200
5/5 [==============================] - 0s 2ms/step - loss: 0.6928 - accuracy: 0.5714
Epoch 4/200
5/5 [==============================] - 0s 2ms/step - loss: 0.6926 - accuracy: 0.5714
Epoch 5/200
5/5 [==============================] - 0s 2ms/step - loss: 0.6925 - accuracy: 0.5714
Epoch 6/200
5/5 [==============================] - 0s 2ms/step - loss: 0.6923 - accuracy: 0.5714
Epoch 7/200
5/5 [==============================] - 0s 2ms/step - loss: 0.6923 - accuracy: 0.5714
Epoch 8/200
5/5 [==============================] - 0s 2ms/step - loss: 0.6919 - accuracy: 0.5714
Epoch 9/200
5/5 [==============================] - 0s 2ms/step - loss: 0.6917 - accuracy: 0.5714
Epoch 10/200
5/5 [==============================] - 0s 2ms/step - loss: 0.6913 - accuracy: 0.5714
Epoch 11/200
5/5 [===========

***Predicting the Test data Results***

In [ ]:
ANN.evaluate(X_test,Y_test)
Y_pred=ANN.predict(X_test)
Y_pred=(Y_pred>0.5)                   # output obtained by sigmoid function >0.5 is predicted as 1 and <0.5 is predicted as 0
print(np.concatenate((Y_pred.reshape(len(Y_pred),1),np.array(Y_test).reshape(len(Y_test),1)),1))  # comapring Y_test and Y_pred

1/1 [==============================] - 0s 143ms/step - loss: 0.2311 - accuracy: 1.0000
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]]


***Making the Confusion Matrix for our prediction***

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(Y_test,Y_pred))
print("Accuracy score : ",accuracy_score(Y_test,Y_pred))

[[1 0]
 [0 5]]
Accuracy score :  1.0




---


**2. Customer Churn Prediction Model using ANN**


---




In [ ]:
# importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf    

***importing the dataset [Churn_Modelling.csv](https://www.kaggle.com/mltuts/churn-modelling-data?select=Churn_Modelling.csv)***

In [ ]:
# loading the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
# preparing the dataset in required format
# assigning values to independent and dependent variable
X = dataset.iloc[:,3:-1]
Y = dataset.iloc[:,-1]
print(X)
print(Y)

# Encoding the Categorical data

from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder()
X.iloc[:, 2] = le.fit_transform(X.iloc[:, 2])

# Encoding the Geography data with one hot encoder

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[1])] , remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

print(X)
print(Y)

      CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0           

In [ ]:
# Splitting the X and Y Dataset into the Training set and Test set
# Splitting the dataset into 20% test data and 80% train data
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0) 

In [ ]:
# Printing the splitted data
print("X Train\n",X_train)
print("Y Train\n",Y_train)
print("X test\n",X_test)
print("Y test\n",Y_test)

X Train
 [[0.0000000e+00 0.0000000e+00 1.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 1.6383064e+05]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  1.0000000e+00 5.7098000e+04]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 1.8563076e+05]
 ...
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 1.8142987e+05]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00 ... 1.0000000e+00
  1.0000000e+00 1.4875016e+05]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 1.1885526e+05]]
Y Train
 7389    0
9275    0
2995    0
5316    0
356     0
       ..
9225    0
4859    0
3264    0
9845    0
2732    1
Name: Exited, Length: 8000, dtype: int64
X test
 [[0.0000000e+00 1.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  1.0000000e+00 1.9285267e+05]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 1.2870210e+05]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00 ... 1.0000000e+00
  1.0000000

In [ ]:
# Perform Feature Scaling - Standardizing the dataset
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [ ]:
# printing values after feature scaling
print("X Train\n",X_train)
print("X Test\n",X_test)

X Train
 [[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]
X Test
 [[-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
   1.61085707]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   0.49587037]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   0.71888467]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -1.54507805]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   1.61255917]]


***Building the Artificial Neural Network***

In [ ]:
# Importing keras
import keras
from keras.models import Sequential  
from keras.layers import Dense

***Initializing the Artificial Neural Network***

In [ ]:
ANN = Sequential()

***Adding the input and first hidden layer***
***
1.   input layer nodes : X.shape[1]
2.   1st hidden layer nodes : 20
3.   Activation Function : Relu
***

In [ ]:
ANN.add(Dense(20,kernel_initializer='uniform',activation='relu',input_dim=X.shape[1]))

***Adding the second hidden layer***
***
1.   input layer nodes : 20 (output of 1st hidden layer)
2.   2nd hidden layer nodes : 20
3.   Activation Function : Relu
***


In [ ]:
ANN.add(Dense(20,kernel_initializer='uniform',activation='relu',input_dim=20))

***Adding the output layer***
***
*   Output layer nodes : 1
***

In [ ]:
ANN.add(Dense(1,kernel_initializer='uniform',activation='sigmoid'))

***Training the Artificial Neural Network***<br>
***compile :***
***
*   optimizer : "adam" performs gradient descent
*   cost function : binary_crossentropy

***

In [ ]:
ANN.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

***Fitting the ANN to Training Set***

In [ ]:
ANN.fit(X_train,Y_train,epochs=200)

Epoch 1/200
250/250 [==============================] - 1s 1ms/step - loss: 0.5045 - accuracy: 0.7954
Epoch 2/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4275 - accuracy: 0.7960
Epoch 3/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4218 - accuracy: 0.8040
Epoch 4/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4160 - accuracy: 0.8255
Epoch 5/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4123 - accuracy: 0.8313
Epoch 6/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4097 - accuracy: 0.8347
Epoch 7/200
250/250 [==============================] - 0s 2ms/step - loss: 0.4066 - accuracy: 0.8363
Epoch 8/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4045 - accuracy: 0.8353
Epoch 9/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4029 - accuracy: 0.8349
Epoch 10/200
250/250 [==============================] - 0s 2ms/step - loss: 0.4015 - accura

***Predicting the Test data Results***

In [ ]:
ANN.evaluate(X_test,Y_test)
Y_pred=ANN.predict(X_test)
Y_pred=(Y_pred>0.5)                   # output obtained by sigmoid function >0.5 is predicted as 1 and <0.5 is predicted as 0
print(np.concatenate((Y_pred.reshape(len(Y_pred),1),np.array(Y_test).reshape(len(Y_test),1)),1))  # comparing the Y_test and Y_pred

63/63 [==============================] - 0s 1ms/step - loss: 0.3415 - accuracy: 0.8585
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


***Making the Confusion Matrix for our prediction***

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(Y_test,Y_pred))
print("Accuracy score : ",accuracy_score(Y_test,Y_pred))

[[1493  102]
 [ 181  224]]
Accuracy score :  0.8585




---





---

